{
    "config": {
        "abort": {
            "already_configured": "Compte d\u00e9j\u00e0 configur\u00e9",
            "reauth_failed_existing": "Impossible de mettre \u00e0 jour l'entr\u00e9e de configuration, veuillez supprimer l'int\u00e9gration et la configurer \u00e0 nouveau.",
            "unknown": "Erreur inattendue"
        },
        "error": {
            "cannot_connect": "Echec de la connexion",
            "invalid_api_key": "Cl\u00e9 API non valide",
            "reauth_failed_matching_account": "La cl\u00e9 API que vous avez fournie ne correspond pas \u00e0 l\u2019ID de compte pour la configuration existante.",
            "unknown": "Erreur inattendue"
        },
        "step": {
            "reauth_confirm": {
                "data": {
                    "api_key": "Cl\u00e9 API"
                },
                "description": "Vous devez fournir une nouvelle cl\u00e9 API en lecture seule \u00e0 partir d'Uptime Robot"
            },
            "user": {
                "data": {
                    "api_key": "Cl\u00e9 API"
                },
                "description": "Vous devez fournir une cl\u00e9 API en lecture seule \u00e0 partir d'Uptime Robot"
            }
        }
    }
}